services:
  next_db:
    image: mysql:8.0
    container_name: next_db
    environment:
      MYSQL_ROOT_PASSWORD: dimonggoin123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: dimonggoin123
    ports:
      - "6633:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - nast_app
  nast_app:
    container_name: nast_app
    depends_on:
      - next_db
    ports:
      - "85:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - .env:/app/.env
      - ./:/app
    networks:
      - nast_app
volumes:
   dbdata:
networks:
  nast_app:
