services:
  next_db:
     image: mysql:8.0
     container_name: db
     environment:
       MYSQL_ROOT_PASSWORD: dimonggoin123
       MYSQL_DATABASE: app_db
       MYSQL_USER: app_user
       MYSQL_PASSWORD: dimonggoin123
     ports:
       - "6033:3306"
     volumes:
       - dbdata:/var/lib/mysql
  nast_app:
    ports:
      - "85:85"
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .env:/app/.env
volumes:
   dbdata: